<?php
$elements = array(
    'title_1' => 'Sway3, le soutien scolaire social',
    'para_1' => "Avec le soutien scolaire en ligne sway3, vous pouvez avoir de l'aide à distance pour dépasser vos difficultés au niveau de cours.",
    'btn_1' => 'Se connecter étudiant',
    'btn_2' => 'Se connecter formateur',
    'title_2' => 'Comment ça fonctionne ?',
    'para_2' => "Inscrivez-vous  en renseignant le formulaire d'inscription. postez votre problématique ou participez à une séance de soutien ouverte.",
    'btn_3' => 'Inscrivez-vous',
    'sing' => 'Les Développeurs:',
    'contact' => 'Contactez-nous',
    'passO' => 'Mot de passe Oublié ?',
    'filiere' => ' Choisir une filière',
    'niveau' => 'Niveau Scolaire',
    'btn' => 'Connectez-vous',
    'mode' => 'Mot de passe',
    'mail' => 'Votre adresse Gmail',
    'mode2' => 'Confirmer Mot de passe',
    'name' => 'Votre Nom',
    'name2' => 'Votre prénom',
    'btn1_navbar' => 'Se connecter',
    'btn2_navbar' => 'S’inscrire',
);
